{
 "title": "대시보드",
 "description": "Métricas de Quantidade de request de sucesso, erro, warning, spring data, entity, resilience retry, CPU e memória e outros, esse dash foi corrigido alguns erros que foi publicado na versão anterior.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": {
     "query": "label_values(resilience4j_retry_calls_total{application=\"$application\", instance=\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "기본 통계",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "서버",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "\b업타임",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "최근 \b서버 시동 시간",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "HTTP 통계",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API 요청량 (2XX only)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=~\"2.*\"}[30s])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Req / Sec",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "API 요청 추세",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\"}[30s])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Status Code HTTP Request",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"200\"}[$__range]))",
     "legendFormat": "200"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"201\"}[$__range]))",
     "legendFormat": "201"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"202\"}[$__range]))",
     "legendFormat": "202"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"204\"}[$__range]))",
     "legendFormat": "204"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"400\"}[$__range]))",
     "legendFormat": "400"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"401\"}[$__range]))",
     "legendFormat": "401"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"403\"}[$__range]))",
     "legendFormat": "403"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"409\"}[$__range]))",
     "legendFormat": "409"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"408\"}[$__range]))",
     "legendFormat": "408"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"404\"}[$__range]))",
     "legendFormat": "404"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"500\"}[$__range]))",
     "legendFormat": "500"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"502\"}[$__range]))",
     "legendFormat": "502"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"503\"}[$__range]))",
     "legendFormat": "503"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=\"504\"}[$__range]))",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "API 요청 횟수 누적 카운트",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "전체 API 요청 횟수",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "업로드 된 게시글 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{application=\"$application\", uri=\"/v1/posts\", method=\"POST\", status=\"200\"}[$__range])"
    }
   ]
  },
  {
   "title": "가입자 수",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{application=\"$application\", uri=\"/v1/auth/register\", method=\"POST\", status=\"200\"}[$__range])"
    }
   ]
  },
  {
   "title": "성공 응답 횟수 (2XX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=~\"2.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "경고 응답 횟수 (4XX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=~\"4.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "실패 응답 횟수 (5XX)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\", status=~\"5.*\"}[$__range]))"
    }
   ]
  },
  {
   "title": "API 요청의 단일 최대 처리 시간 (sec) (2XX only)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"$instance\", application=\"$application\", status=~\"2.*\", uri!~\".*actuator.*\", uri!~\".*swagger*.*\", uri!~\".*api-docs*.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "API 요청의 누적 처리 시간 (sec) (2XX only)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", uri!~\".*swagger*.*\", uri!~\".*actuator.*\", uri!~\".*api-docs*.*\", status=~\"2.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HikariCP 통계",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{application=\"$application\",instance=\"$instance\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "repeat": "memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
     "repeat": "memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_classes_unloaded_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "Classes Unloaded"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Classes Loaded"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Log Event (1m)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(logback_events_total{application=\"$application\", instance=~\"$instance\"}[1m])",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  }
 ]
}